# 配置文件

DAILY_TIME: "8:00" # 每日定时发送时间。该时间为系统时间，如果当前系统时间不为北京时间需要自行进行换算

START_DATE: "2022-01-01" # 纪念日
CITY: "三河市"

BIRTHDAY:
  - "11-01"

APP_ID: "wx244862b7767d9c9a"
APP_SECRET: "81fbfecbc4544f79ab6492138f901b9a"

USER_ID: 
  - "oJtmN6EGZkbOpe5kDxM5N7o8ngVM"
TEMPLATE_ID: "xT-Gg4-_id5L_72_xQcYRKrXeqTlC-wYkJXdy-hGfCw"
